### ISSUE TITLE
"en able to find the main Scilab class. Check if the Scilab and thirdparty packages are available"

### ISSUE THREAD

**Issue by Acentelles** [Calysto/scilab_kernel#18]
Hi! I'm having the following error. My kernel seems to start correctly but when I enter "Ctrl+Enter" in the Scilab notebook, I get this error:
```
I 22:31:51.057 NotebookApp] Kernel started: e5fdc58d-65a8-4384-b708-c1e5427533e3
[MetaKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/media/acentelles/centelles/programs/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/media/acentelles/centelles/programs/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/media/acentelles/centelles/programs/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/media/acentelles/centelles/programs/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 541, in execute_request
    user_expressions, allow_stdin,
  File "/media/acentelles/centelles/programs/anaconda3/lib/python3.7/site-packages/metakernel/_metakernel.py", line 395, in do_execute
    retval = self.do_execute_direct(code)
  File "/media/acentelles/centelles/programs/anaconda3/lib/python3.7/site-packages/scilab_kernel/kernel.py", line 116, in do_execute_direct
    self.handle_plot_settings()
  File "/media/acentelles/centelles/programs/anaconda3/lib/python3.7/site-packages/scilab_kernel/kernel.py", line 184, in handle_plot_settings
    super(ScilabKernel, self).do_execute_direct('\n'.join(cmds), True)
  File "/media/acentelles/centelles/programs/anaconda3/lib/python3.7/site-packages/metakernel/process_metakernel.py", line 60, in do_execute_direct
    self.wrapper = self.makeWrapper()
  File "/media/acentelles/centelles/programs/anaconda3/lib/python3.7/site-packages/scilab_kernel/kernel.py", line 101, in makeWrapper
    continuation_prompt_regex=continuation_prompt)
  File "/media/acentelles/centelles/programs/anaconda3/lib/python3.7/site-packages/metakernel/replwrap.py", line 106, in __init__
    self._expect_prompt()
  File "/media/acentelles/centelles/programs/anaconda3/lib/python3.7/site-packages/metakernel/replwrap.py", line 138, in _expect_prompt
    pos = self.child.expect(expects, timeout=timeout)
  File "/media/acentelles/centelles/programs/anaconda3/lib/python3.7/site-packages/pexpect/spawnbase.py", line 344, in expect
    timeout, searchwindowsize, async_)
  File "/media/acentelles/centelles/programs/anaconda3/lib/python3.7/site-packages/pexpect/spawnbase.py", line 372, in expect_list
    return exp.expect_loop(timeout)
  File "/media/acentelles/centelles/programs/anaconda3/lib/python3.7/site-packages/pexpect/expect.py", line 179, in expect_loop
    return self.eof(e)
  File "/media/acentelles/centelles/programs/anaconda3/lib/python3.7/site-packages/pexpect/expect.py", line 122, in eof
    raise exc
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
<pexpect.pty_spawn.spawn object at 0x7f187db1ab90>
command: /usr/bin/scilab-adv-cli
args: [b'/usr/bin/scilab-adv-cli']
buffer (last 100 chars): ''
before (last 100 chars): 'en able to find the main Scilab class. Check if the Scilab and thirdparty packages are available).\r\n'
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: None
flag_eof: True
pid: 17285
child_fd: 45
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile('-->')
    1: re.compile('  >')
    2: re.compile('PEXPECT_PROMPT+')
```

I'm using Ubuntu 20.04. Let me know if I can provide any more details. Thank you

**Comment by blink1073** [comment]
Hi @Acentelles, are you able to run `/usr/bin/scilab-adv-cli` directly without error?  From the traceback it looks like it might not be functional: `en able to find the main Scilab class. Check if the Scilab and thirdparty packages are available`.

**Comment by Supriyo-455** [comment]
@Acentelles same here! Scilab gui not working but scilab cli working..
