### ISSUE TITLE
Scilab kernel fails to start under Windows

### ISSUE THREAD

**Issue by mottelet** [Calysto/scilab_kernel#45]
Latest Scilab kernel does not start under Windows 10 (with latest Python 3.12)
```
AttributeError: module 'importlib' has no attribute 'find_loader'
[I 2024-02-26 10:25:37.789 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (5/5), new random ports
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\steph\AppData\Roaming\Python\Python312\site-packages\scilab_kernel\__main__.py", line 2, in <module>
    from .kernel import ScilabKernel
  File "C:\Users\steph\AppData\Roaming\Python\Python312\site-packages\scilab_kernel\kernel.py", line 12, in <module>
    if importlib.find_loader('winreg")
```

**Comment by mottelet** [comment]
See https://gitlab.com/ase/ase/-/issues/1256. find_loader was already deprecated and has been removed in 3.12.
